version: '3.8'

services:

  php-fpm:
    restart: always
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: php-fpm
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network
    user: www-data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - app-network

  node:
    image: node:18
    container_name: node
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5443:5432"

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
